import type { NextPage } from 'next';
import Head from 'next/head';
import { useState } from 'react';
import styles from '../styles/Home.module.css';
import axios from 'axios';

const Home: NextPage = () => {
	const [name1, setName1] = useState('');
	const [loader1, setLoader1] = useState(false);
	const [name2, setName2] = useState('');
	const [loader2, setLoader2] = useState(false);

	const getName1 = async () => {
		try {
			setLoader1(true);
			const response = await axios.get('/api/test');
			setName1(response?.data?.name);
		} catch (e) {
			console.error(e);
		} finally {
			setLoader1(false);
		}
	};

	const getName2 = async () => {
		try {
			setLoader2(true);
			const response = await axios.put('/api/test/1');
			setName2(response?.data?.name);
		} catch (e) {
			console.error(e);
		} finally {
			setLoader2(false);
		}
	};

	return (
		<div className={styles.container}>
			<Head>
				<title>Create Next App</title>
				<meta name="description" content="Generated by create next app" />
				<link rel="icon" href="/favicon.ico" />
			</Head>

			<main className={styles.main}>
				<p>{loader1 ? 'loading...' : name1}</p>
				<button onClick={getName1}>/api/test</button>
				<p>{loader2 ? 'loading...' : name2}</p>
				<button onClick={getName2}>/api/test/1</button>
			</main>
		</div>
	);
};

export default Home;
